package ar.edu.unlam.pb1;

public enum DatosAModificar {
	CALLE, NUMERO, LOCALIDAD, PRECIO, DISPONIBILIDAD, TIPO_DE_OPERACION, PISO, DEPARTAMENTO, NUMERO_PH,
	METROS_CUADRADOS_TERRENO, HECTAREAS_CAMPO
}
