package ar.edu.unlam.pb1;

public enum OpcionMenu {
	//prueba git

	AGREGAR_PROPIEDAD, MODIFICAR_PROPIEDAD, AGREGAR_CLIENTE, OBTENER_LISTADO_POR_PRECIO, OBTENER_LISTADO_POR_UBICACION,
	BUSCAR_PROPIEDAD_POR_PRECIO, BUSCAR_PROPIEDAD_POR_UBICACION, REALIZAR_VENTA, REALIZAR_ALQUILER,
	CALCULAR_EL_PRECIO_PROMEDIO_DE_LAS_CASAS, SALIR
}
