package ar.edu.unlam.pb1;

public enum OpcionMenu {
	AGREGAR_PROPIEDAD, MOSTRAR_PROPIEDADES, MODIFICAR_PROPIEDAD, AGREGAR_CLIENTE, OBTENER_LISTADO_POR_PRECIO, OBTENER_LISTADO_POR_UBICACION,
	BUSCAR_PROPIEDAD_POR_PRECIO, BUSCAR_PROPIEDAD_POR_UBICACION,
	BUSCAR_PROPIEDAD_POR_VENTA_Y_ALQUILER, REALIZAR_VENTA, REALIZAR_ALQUILER,
	CALCULAR_EL_PRECIO_PROMEDIO, SALIR
}
